server {
	listen 8080;
	server_name localhost;

	location / {
		root /app/content;
		index index2.html index.php index.py;
	}

	location /upload {
		root /app/content/upload;
	}

	location /images {
		alias /app/content/images/;
		error_page   404.html;
	}

	location /sessions {
		alias /app/content/sessions/;
		error_page   404.html;
	}
}
