server {
	listen 8080;
	listen [::]:8080;
	# listen 9090;
	# listen 444;
	server_name localhost;

	# location / {
	# 	# root /var/www/html;
		root /var/www/bonus-website;
		# root /Users/gabrielfernandezleroux/Downloads/webserv17feb253pm/inception/srcs/requirements/bonus/website/content
		index index.html;
	# }
		location /redirme {
		root /hello_world;
		limit_except POST DELETE;
		client_max_body_size 1;
		# return 301 /error;
		}

		location /error {
			client_max_body_size 1;
			return 500;
		}

		location /php {
		client_max_body_size 1;
		root /var/www/bonus-website;
		}

		location /images {
        alias /var/www/images;
    	}
}

server {
listen 8080;
server_name server42.com;

location / {
		# root /var/www/api;
root /var/www/bonus-website/15.png;
		# root /Users/gabrielfernandezleroux/Downloads/webserv17feb253pm/inception/srcs/requirements/bonus/website/content/15.png
index index.php;
}
}

server {
	listen 8080;
	server_name api.dosmyserver.com;

	location / {
		# root /var/www/api;
		root /var/www/bonus-website/15.png;
		# root /Users/gabrielfernandezleroux/Downloads/webserv17feb253pm/inception/srcs/requirements/bonus/website/content/15.png
		index index.php;
	}
}

server {
	listen 9090;
	server_name api.myserver.com;

	location / {
		# root /var/www/api;
		root /var/www/bonus-website/15.png;
		# If root is set to a file, Nginx will fail to start or fail to serve files properly.
		# root /Users/gabrielfernandezleroux/Downloads/webserv17feb253pm/inception/srcs/requirements/bonus/website/content/15.png
		index index.php;
	}
}

# server {
# 	listen       443 ssl;
# 	listen  [::]:443 ssl;
# 	server_name  $DOMAIN_NAME;

# 	ssl_protocols TLSv1.3;

# 	ssl_certificate     /etc/nginx/ssl/nginx_cert.pem;
#     ssl_certificate_key /etc/nginx/ssl/nginx_key.pem;

# 	#access_log  /var/log/nginx/host.access.log  main;

# 	location / {
# 		root   /var/www/html;
# 		index  index.php index.html index.htm;
# 	}

# 	#error_page  404              /404.html;

# 	# redirect server error pages to the static page /50x.html
# 	error_page   500 502 503 504  /50x.html;
# 	location = /50x.html {
# 		root   /var/www/html;
# 	}

# server {
#     listen       9092;
#     server_name  $DOMAIN_BONUS;

#     ssl_protocols TLSv1.3;

#     ssl_certificate     /etc/nginx/ssl/nginx_cert.pem;
#     ssl_certificate_key /etc/nginx/ssl/nginx_key.pem;

#     location / {
#         root   /var/www/bonus-website;
#         index  index.html;
#     }

#     error_page  404 /404.html;
#     location = /404.html {
#         root /var/www/bonus-website;
#     }
# }